import { MeterData } from "../../types/meter";
import { ADD_DATA } from "../constants/actionTypes";

const defaultState = {
    volt_l1: 0,
    volt_l2: 0,
    volt_l3: 0,
    curr_l1: 0,
    curr_l2: 0,
    curr_l3: 0,
    act_pwr_l1: 0,
    act_pwr_l2: 0,
    act_pwr_l3: 0,
    apt_pwr_l1: 0,
    apt_pwr_l2: 0,
    apt_pwr_l3: 0,
    rct_pwr_l1: 0,
    rct_pwr_l2: 0,
    rct_pwr_l3: 0,
    pf_l1: 0,
    pf_l2: 0,
    pf_l3: 0,
    pa_l1: 0,
    pa_l2: 0,
    pa_l3: 0,
    avg_volt_ln: 0,
    avg_curr_ln: 0,
    total_curr_ln: 0,
    total_act_pwr: 0,
    total_apt_pwr: 0,
    total_rct_pwr: 0,
    total_pf: 0,
    total_pa: 0,
    freq: 0,
    imp_wh_last_reset: 0,
    exp_wh_last_reset: 0,
    imp_varh_last_reset: 0,
    exp_varh_last_reset: 0,
    vah_last_reset: 0,
    ah_last_reset: 0,
    total_sys_pwr_dmd: 0,
    max_sys_pwr_dmd: 0,
    imp_act_pwr_dmd: 0,
    imp_max_act_pwr_dmd: 0,
    exp_act_pwr_dmd: 0,
    max_exp_act_pwr_dmd: 0,
    total_apt_pwr_dmd: 0,
    max_apt_pwr_dmd: 0,
    total_curr_dmd: 0,
    max_curr_dmd: 0,
    total_rct_pwr_dmd: 0,
    max_rct_pwr_dmd: 0,
    volt_p_seq: 0,
    curr_p_seq: 0,
    nat_load: 0,
    nat_load_l1: 0,
    nat_load_l2: 0,
    nat_load_l3: 0,
    volt_l1_l2: 0,
    volt_l2_l3: 0,
    volt_l3_l1: 0,
    avg_l2l: 0,
    curr_neut: 0,
    volt_thd_l1: 0,
    volt_thd_l2: 0,
    volt_thd_l3: 0,
    curr_thd_l1: 0,
    curr_thd_l2: 0,
    curr_thd_l3: 0,
    avg_volt_thd: 0,
    avg_curr_thd: 0,
    curr_dmd_l1: 0,
    curr_dmd_l2: 0,
    curr_dmd_l3: 0,
    max_curr_dmd_l1: 0,
    max_curr_dmd_l2: 0,
    max_curr_dmd_l3: 0,
    volt_l1_l2_thd: 0,
    volt_l2_l3_thd: 0,
    volt_l3_l1_thd: 0,
    avg_thd_ln: 0,
    total_kwh: 0,
    total_kvarh: 0,
    imp_l1_kwh: 0,
    imp_l2_kwh: 0,
    imp_l3_kwh: 0,
    exp_l1_kwh: 0,
    exp_l2_kwh: 0,
    exp_l3_kwh: 0,
    total_l1_kwh: 0,
    total_l2_kwh: 0,
    total_l3_kwh: 0,
    imp_l1_kvarh: 0,
    imp_l2_kvarh: 0,
    imp_l3_kvarh: 0,
    exp_l1_kvarh: 0,
    exp_l2_kvarh: 0,
    exp_l3_kvarh: 0,
    total_l1_kvarh: 0,
    total_l2_kvarh: 0,
    total_l3_kvarh: 0,
    volt_l1_harmonic: [],
    volt_l2_harmonic: [],
    volt_l3_harmonic: [],
    curr_l1_harmonic: [],
    curr_l2_harmonic: [],
    curr_l3_harmonic: [],
    volt_l1_total_harmonic: 0,
    volt_l2_total_harmonic: 0,
    volt_l3_total_harmonic: 0,
    curr_l1_total_harmonic: 0,
    curr_l2_total_harmonic: 0,
    curr_l3_total_harmonic: 0
} as MeterData;

export default function dataReducer(state = defaultState, action: any) {
    switch(action.type) {
        case ADD_DATA:
            const json = JSON.parse(action.payload);
            json['volt_l1_harmonic'] = json['volt_l1_harmonic'] ? JSON.parse(json['volt_l1_harmonic']) : [];
            json['volt_l2_harmonic'] = json['volt_l2_harmonic'] ? JSON.parse(json['volt_l2_harmonic']) : [];
            json['volt_l3_harmonic'] = json['volt_l3_harmonic'] ? JSON.parse(json['volt_l3_harmonic']) : [];
            json['curr_l1_harmonic'] = json['curr_l1_harmonic'] ? JSON.parse(json['curr_l1_harmonic']) : [];
            json['curr_l2_harmonic'] = json['curr_l2_harmonic'] ? JSON.parse(json['curr_l2_harmonic']) : [];
            json['curr_l3_harmonic'] = json['curr_l3_harmonic'] ? JSON.parse(json['curr_l3_harmonic']) : [];
            return json;
        default:
            return state;
    }
}