const MeterUnit: {[key:string]:any} = {
    volt_l1: 'V',
    volt_l2: 'V',
    volt_l3: 'V',
    curr_l1: 'A',
    curr_l2: 'A',
    curr_l3: 'A',
    act_pwr_l1: 'W',
    act_pwr_l2: 'W',
    act_pwr_l3: 'W',
    apt_pwr_l1: 'VA',
    apt_pwr_l2: 'VA',
    apt_pwr_l3: 'VA',
    rct_pwr_l1: 'VAr',
    rct_pwr_l2: 'VAr',
    rct_pwr_l3: 'VAr',
    pf_l1: 'PF',
    pf_l2: 'PF',
    pf_l3: 'PF',
    pa_l1: '°',
    pa_l2: '°',
    pa_l3: '°',
    avg_volt_ln: 'V',
    avg_curr_ln: 'A',
    total_curr_ln: 'A',
    total_act_pwr: 'W',
    total_apt_pwr: 'VA',
    total_rct_pwr: 'VAr',
    total_pf: 'PF',
    total_pa: '°',
    freq: 'Hz',
    imp_wh_last_reset: 'kWh',
    exp_wh_last_reset: 'kWH',
    imp_varh_last_reset: 'kVArh',
    exp_varh_last_reset: 'kVArh',
    vah_last_reset: 'kVAh',
    ah_last_reset: 'Ah',
    total_sys_pwr_dmd: 'W',
    max_sys_pwr_dmd: 'W',
    imp_act_pwr_dmd: 'W',
    imp_max_act_pwr_dmd: 'W',
    exp_act_pwr_dmd: 'W',
    max_exp_act_pwr_dmd: 'W',
    total_apt_pwr_dmd: 'VA',
    max_apt_pwr_dmd: 'VA',
    total_curr_dmd: 'Amps',
    max_curr_dmd: 'Amps',
    total_rct_pwr_dmd: 'VAr',
    max_rct_pwr_dmd: 'VAr',
    volt_p_seq: '',
    curr_p_seq: '',
    nat_load: '',
    nat_load_l1: '',
    nat_load_l2: '',
    nat_load_l3: '',
    volt_l1_l2: 'V',
    volt_l2_l3: 'V',
    volt_l3_l1: 'V',
    avg_l2l: 'V',
    curr_neut: 'A',
    volt_thd_l1: '%',
    volt_thd_l2: '%',
    volt_thd_l3: '%',
    curr_thd_l1: '%',
    curr_thd_l2: '%',
    curr_thd_l3: '%',
    avg_volt_thd: '%',
    avg_curr_thd: '%',
    curr_dmd_l1: 'A',
    curr_dmd_l2: 'A',
    curr_dmd_l3: 'A',
    max_curr_dmd_l1: 'A',
    max_curr_dmd_l2: 'A',
    max_curr_dmd_l3: 'A',
    volt_l1_l2_thd: '%',
    volt_l2_l3_thd: '%',
    volt_l3_l1_thd: '%',
    avg_thd_ln: '%',
    total_kwh: 'kWh',
    total_kvarh: 'kVArh',
    imp_l1_kwh: 'kWh',
    imp_l2_kwh: 'kWh',
    imp_l3_kwh: 'kWh',
    exp_l1_kwh: 'kWh',
    exp_l2_kwh: 'kWh',
    exp_l3_kwh: 'kWh',
    total_l1_kwh: 'kWh',
    total_l2_kwh: 'kWh',
    total_l3_kwh: 'kWh',
    imp_l1_kvarh: 'kVArh',
    imp_l2_kvarh: 'kVArh',
    imp_l3_kvarh: 'kVArh',
    exp_l1_kvarh: 'kVArh',
    exp_l2_kvarh: 'kVArh',
    exp_l3_kvarh: 'kVArh',
    total_l1_kvarh: 'kVArh',
    total_l2_kvarh: 'kVArh',
    total_l3_kvarh: 'kVArh',
    volt_l1_total_harmonic: '%',
    volt_l2_total_harmonic: '%',
    volt_l3_total_harmonic: '%',
    curr_l1_total_harmonic: '%',
    curr_l2_total_harmonic: '%',
    curr_l3_total_harmonic: '%',
}

export const getUnit = (key: string): string => {
    return MeterUnit[key];
}

export const naturalLoad = (val: number): string => {
    switch(val){
        case 1: return 'Resistive';
        case 2: return 'Inductive';
        case 3: return 'Capacitive';
        default: return '';
    }
}